apiVersion: v1
kind: Service
metadata:
  name: node-js-sample
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: node-js-sample
  sessionAffinity: None
  type: NodePort
