name: CI-pipeline
'on':
  push:
    branches:
      - master    
jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          id
          npm i
          npm run build
          cd functions
          npm i
          cd -  
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t <my.container.registry.io>/<my_app>:<my_tag> .
          - docker push <my.container.registry.io>/<my_app>:<my_tag>
        services:
          - docker
